[package]
name = "vac"
version = "0.1.0"
authors = ["Chris Joseph Gallo <chrisjg3@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
